name: aiscript
description: Parser and interpreter for AiScript, a lightweight scripting language, written in Dart.
version: 0.5.0
repository: https://github.com/LeadRDRK/aiscript-dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  es6_math: ^1.2.1
  path: ^1.8.3
  petitparser: ^5.4.0
  uuid: ^3.0.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
